### ISSUE TITLE
Issues Generating Test Cases with riscv-ctg-0.11.0

### ISSUE THREAD

**Issue by kobeyu** [riscv-software-src/riscv-ctg#66]
Hi 

I followed the instructions in the doc to generate test cases, but I encountered the following problem(*1).

cmd: riscv_ctg -v debug -d ./tests/ -r -cf ./sample_cgfs/dataset.cgf -cf ./sample_cgfs/rv32i.cgf -bi rv32i -p2

Version Information:
os:Linux geralt 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Python Package:
riscv-ctg-0.11.0 (installed via 'pip install riscv-ctg')
ruamel.yaml: ruamel.yaml 0.17.32

(*1) Error message:
    INFO | ****** RISC-V Compliance Test Generator 0.11.0 *******
    INFO | Copyright (c) 2020, InCore Semiconductors Pvt. Ltd.
    INFO | All Rights Reserved.
    INFO | Copying env folder to Output directory.
Traceback (most recent call last):
  File "/home/msyu/workspace/venv/bin/riscv_ctg", line 8, in <module>
    sys.exit(cli())
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/msyu/workspace/project_rvv_testsuite/riscv-ctg/riscv_ctg/main.py", line 29, in cli
    ctg(verbose, out_dir, randomize ,xlen, int(flen), cgf,procs,base_isa,inst)
  File "/home/msyu/workspace/project_rvv_testsuite/riscv-ctg/riscv_ctg/ctg.py", line 126, in ctg
    op_template = utils.load_yamls(const.template_files)
  File "/home/msyu/workspace/project_rvv_testsuite/riscv-ctg/riscv_ctg/utils.py", line 65, in load_yamls
    return dict(yaml.load(fp))
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 426, in load
    return constructor.get_single_data()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 70, in get_single_node
    document = self.compose_document()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 92, in compose_document
    node = self.compose_node(None, None)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 209, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 209, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 104, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 139, in check_event
    self.current_event = self.state()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 617, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1728, in check_token
    self._gather_comments()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1768, in _gather_comments
    self.fetch_more_tokens()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 292, in fetch_more_tokens
    return self.fetch_literal()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 675, in fetch_literal
    self.fetch_block_scalar(style='|')
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 686, in fetch_block_scalar
    self.tokens.append(self.scan_block_scalar(style))
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1930, in scan_block_scalar
    return Scanner.scan_block_scalar(self, style, rt=rt)
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1120, in scan_block_scalar
    breaks, max_indent, end_mark = self.scan_block_scalar_indentation()
  File "/home/msyu/workspace/venv/lib/python3.8/site-packages/ruamel/yaml/scanner.py", line 1309, in scan_block_scalar_indentation
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: more indented follow up line than first in a block scalar
  in "<file>", line 1484, column 5

**Comment by kobeyu** [comment]
I've figured out the problem. If using the newer version of ruamel.yaml (0.17.32), you'll encounter this issue. However, if you use a slightly earlier version like 0.17.21, it works fine. I don't know if we need to update the YAML files currently in the repo.
